#!/bin/sh

usage () {
    echo "Usage: $0 [-d cdrom_dir]"
    exit 1
}

make_dir () {
    if [ ! -d "$1" ]; then
	mkdir -p $1
    fi
}

CDROM_DIR=/mnt/cdrom
PERL=perl
BASE_DIR=`dirname $0`
SRC_DIR=$BASE_DIR/scripts/KyotoCorpus4.01-src
DEST_DIR=$BASE_DIR/mainichi
NOTOKEN_DIR=$BASE_DIR/treebank
TOKEN_DIR=$BASE_DIR/full

PYTHON=python
MERGE=$BASE_DIR/scripts/merge-token.py
ARTICLE_RANGE="01 03 04 05 06"
EDITORIAL_RANGE="01 02 03 04"

while getopts d:h OPT
do
    case $OPT in
	d)  CDROM_DIR=$OPTARG
	    ;;
	h)  usage
	    ;;
	*) usage
	    ;;
    esac
done
shift `expr $OPTIND - 1`

if [ ! -f $CDROM_DIR/MAI95.TXT ]; then
    echo "Not found: $CDROM_DIR/MAI95.TXT"
    usage
    exit
fi


make_dir $DEST_DIR

echo "converting MAI95.TXT to SGML ..."
$PERL $SRC_DIR/trans.pl < $CDROM_DIR/MAI95.TXT 2> /dev/null | $PERL $SRC_DIR/mainichi.pl $DEST_DIR

echo "making KyotoCorpus (syn) ..."
#for i in 01 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17
for i in $ARTICLE_RANGE
do
    echo "converting 9501$i ..."
    $PERL $SRC_DIR/format.pl -exed 9501$i < $DEST_DIR/9501.all | $PERL $SRC_DIR/dupli.pl > $DEST_DIR/9501$i.org
done

#for i in 01 02 03 04 05 06 07 08 09 10 11 12
for i in $EDITORIAL_RANGE
do
    echo "converting 95${i}ED ..."
    : > $DEST_DIR/95${i}ED.org
    for j in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
    do
	$PERL $SRC_DIR/format.pl -ed 95$i$j < $DEST_DIR/95$i.all | $PERL $SRC_DIR/dupli.pl >> $DEST_DIR/95${i}ED.org
    done
done


make_dir $TOKEN_DIR

echo "merging texts and trees ..."
for i in $ARTICLE_RANGE
do
    echo "merging 9501$i ..."
    $PYTHON $MERGE $DEST_DIR/9501$i.org $NOTOKEN_DIR/kaede-KTC9501$i.tr > $TOKEN_DIR/kaede-KTC9501$i.tr
    $PYTHON $MERGE --annot morph $DEST_DIR/9501$i.org $NOTOKEN_DIR/kaede-KTC9501$i.morph > $TOKEN_DIR/kaede-KTC9501$i.morph
done
for i in $EDITORIAL_RANGE
do
    echo "merging 95${i}ED ..."
    $PYTHON $MERGE $DEST_DIR/95${i}ED.org $NOTOKEN_DIR/kaede-KTC95${i}ED.tr > $TOKEN_DIR/kaede-KTC95${i}ED.tr
    $PYTHON $MERGE --annot morph $DEST_DIR/95${i}ED.org $NOTOKEN_DIR/kaede-KTC95${i}ED.morph > $TOKEN_DIR/kaede-KTC95${i}ED.morph
done
echo "done"
